// SPDX-FileCopyrightText: © Pokémon/Nintendo/Creatures/GAME FREAK TM, ®, and character names are trademarks of Nintendo.
// SPDX-License-Identifier: LicenseRef-PTCG-ABC-Competition-Use-Only
// Part of the Pokémon TCG AI Battle Challenge. Provided for Competition use only;
// the full license is in the LICENSES/ folder and incorporates the Competition Rules.
// Competition Rules: https://www.kaggle.com/competitions/pokemon-tcg-ai-battle/rules

#pragma once

enum class SelectType : unsigned char {
	None,
	Main,
	Card,
	AttachedCard,
	CardOrAttachedCard,
	Energy,
	Skill,
	Attack,
	Evolve,
	Count,
	YesNo,
	SpecialCondition,
};

constexpr const char* SelectTypeStr[] = {
	"None",
	"Main",
	"Card",
	"AttachedCard",
	"CardOrAttachedCard",
	"Energy",
	"Skill",
	"Attack",
	"Evolve",
	"Count",
	"YesNo",
	"SpecialCondition",
};

enum class SelectContext : unsigned char {
	None,
	Main,
	SetupActivePokemon,
	SetupBenchPokemon,
	Switch,
	ToActive,
	ToBench,
	ToField,
	ToHand,
	Discard,
	ToDeck,
	ToDeckBottom,
	ToPrize,
	NotMove,
	DamageCounter,
	DamageCounterAny,
	Damage,
	RemoveDamageCounter,
	Heal,
	EvolvesFrom,
	EvolvesTo,
	Devolve,
	AttachFrom,
	AttachTo,
	DetachFrom,
	Look,
	EffectTarget,
	DiscardEnergyCard,
	DiscardToolCard,
	SwitchEnergyCard,
	DiscardCardOrAttachedCard,
	DiscardEnergy,
	ToHandEnergy,
	ToDeckEnergy,
	SwitchEnergy,
	SkillOrder,
	Attack,
	DisableAttack,
	Evolve,
	DrawCount,
	DamageCounterCount,
	RemoveDamageCounterCount,
	IsFirst,
	Mulligan,
	Activate,
	FirstEffect,
	MoreDevolve,
	CoinHead,
	AffectSpecialCondition,
	RecoverSpecialCondition,
};

constexpr const char* SelectContextStr[] = {
	"None",
	"Main",
	"SetupActivePokemon",
	"SetupBenchPokemon",
	"Switch",
	"ToActive",
	"ToBench",
	"ToField",
	"ToHand",
	"Discard",
	"ToDeck",
	"ToDeckBottom",
	"ToPrize",
	"NotMove",
	"DamageCounter",
	"DamageCounterAny",
	"Damage",
	"RemoveDamageCounter",
	"Heal",
	"EvolvesFrom",
	"EvolvesTo",
	"Devolve",
	"AttachFrom",
	"AttachTo",
	"DetachFrom",
	"Look",
	"EffectTarget",
	"DiscardEnergyCard",
	"DiscardToolCard",
	"SwitchEnergyCard",
	"DiscardCardOrAttachedCard",
	"DiscardEnergy",
	"ToHandEnergy",
	"ToDeckEnergy",
	"SwitchEnergy",
	"SkillOrder",
	"Attack",
	"DisableAttack",
	"Evolve",
	"DrawCount",
	"DamageCounterCount",
	"RemoveDamageCounterCount",
	"IsFirst",
	"Mulligan",
	"Activate",
	"FirstEffect",
	"MoreDevolve",
	"CoinHead",
	"AffectSpecialCondition",
	"RecoverSpecialCondition",
};

enum class SelectOptionType : unsigned char {
	Number,
	Yes,
	No,
	Card,
	ToolCard,
	EnergyCard,
	Energy,
	Play,
	Attach,
	Evolve,
	Ability,
	Discard,
	Retreat,
	Attack,
	End,
	Skill,
	SpecialCondition,
};

enum class LogType : unsigned char {
	Shuffle,
	HasBasicPokemon,
	TurnStart,
	TurnEnd,
	Draw,
	DrawReverse,
	MoveCard,
	MoveCardReverse,
	Switch,
	Change,
	Play,
	Attach,
	Evolve,
	Devolve,
	MoveAttached,
	Attack,
	HpChange,
	Poisoned,
	Burned,
	Asleep,
	Paralyzed,
	Confused,
	Coin,
	Result,
};

